# Generated by Django 5.0.1 on 2024-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('text', models.TextField(blank=True)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
