# Generated by Django 5.0.1 on 2024-01-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlShort', '0002_shortlink_short_url_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='short_url_key',
        ),
    ]
