# Generated by Django 4.2 on 2024-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShort', '0003_remove_shortlink_short_url_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
